ask/ask/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('qa.urls')),
    url(r'^admin/', admin.site.urls),
]

ask/qa/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.q_new, name='q_new'),
    url(r'^login/$', views.logining, name='logining'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^ask/$', views.q_add, name='q_add'),
    url(r'^popular/$', views.q_popular, name='q_popular'),
    url(r'^new/$', views.test, name='test'),
    url(r'^question/(?P<id>\d+)/$', views.q_details, name='q_details'),
]

ask/qa/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class QuestionManager(models.Manager):

    def new(self):
        return self.order_by('-added_at')

    def popular(self):
        return self.order_by('-rating')


class Question(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    added_at = models.DateTimeField(blank=True, auto_now_add=True)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='likes_set')
    objects = QuestionManager()


class Answer(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(blank=True, auto_now_add=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

ask/qa/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class AskForm(forms.Form):
    title = forms.CharField()
    text = forms.CharField(widget=forms.Textarea)
    

    def clean(self):
        return  self.cleaned_data


    def save(self):
        question = models.Question(**self.cleaned_data)
        return question


class AnswerForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)
    # question_id = forms.CharField(widget=forms.HiddenInput())
    # author = forms.CharField(widget=forms.HiddenInput())


    def clean(self):
        return self.cleaned_data


    def save(self):
        answer = models.Answer(**self.cleaned_data)
        return answer
        
        # answer.save()


class SignupForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(widget=forms.EmailInput)


    def clean_password(self):
        pass
        #make validation here
    
    def clean_email(self):
        pass
        #make validation here

    def clean(self):
        return self.cleaned_data


    def save(self):
        data = self.cleaned_data
        return data


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput) 
    password = forms.CharField(widget=forms.PasswordInput)
    

    def clean(self):
        return self.cleaned_data
        

    def save(self):
        data = self.cleaned_data
        return data

ask/qa/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_GET
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponse
from .models import Question, Answer, QuestionManager
from .forms import AskForm, AnswerForm, LoginForm, SignupForm



def q_details(request, id):
	question = get_object_or_404(Question, id = id)
	if request.method == "POST":
		form = AnswerForm(request.POST)
		if form.is_valid():
			answer = form.save()
			answer.author = request.user
			answer.question_id = id
			answer.save()
			return render(request, 'question.html',{
					'question':		question,
					'form':			form,
					#  остальное пожно прописать сразу в шаблоне
			})
	else:
		form = AnswerForm()

	return render(request, 'question.html',{
		'question':		question,
		'form':			form,
		#  остальное пожно прописать сразу в шаблоне
	})


@require_GET
def q_new(request):
	q_list = Question.objects.new()
	limit = request.GET.get('limit', 10)
	paginator = Paginator(q_list, limit)
	page = request.GET.get('page', 1)
	questions = paginator.page(page)
	return render(request, 'new.html', {
		"questions":	questions,
		# "questions":	q_list,
		# "paginator":	paginator,
		# "page":			page,
	})


@require_GET
def q_popular(request):
	q_list = Question.objects.popular()
	limit = request.GET.get('limit', 10)
	paginator = Paginator(q_list, limit)
	page = request.GET.get('page', 1)
	questions = paginator.page(page)
	return render(request, 'popular.html', {
		"questions":	questions,
		# paginator:	paginator,
		# page:		page,
	})


def test(request, *args, **kwargs):
	return HttpResponse('OK')


def q_add(request):
	if request.method == "POST":
		form = AskForm(request.POST)
		if form.is_valid():
			question = form.save()
			question.author = request.user
			question.save()
			return redirect('q_details', id=question.id)
	else:
		form = AskForm()

	return render(request, 'ask.html', {
		'form':		form
	})


def signup(request):
	error = ''
	if request.method == "POST":
		form = SignupForm(request.POST)
		if form.is_valid():
			user_data = form.save()
			user = User.objects.create_user(user_data['username'], user_data['email'], user_data['password'])
			login(request, user)
			return redirect('q_new')
		else:
			error = 'Something wrong with your data'
	else:
		form = SignupForm()
	
	return render(request, 'signup.html', {
		'error':	error,
		'form':		form,
	})
	

def logining(request):
	error = ''
	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			user_data = form.save()
			user = authenticate(request, username=user_data['username'], password=user_data['password'])
			if user:
				login(request, user)
				return redirect('q_new')
			else:
				error = 'Something wrong'
	else:
		form = LoginForm()

	return render(request, 'login.html', {
		'error':	error,
		'form':		form,
	})

ask/templates/ask.html
{% extends 'base.html'%}


{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

ask/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Ask_project</title>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

ask/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ error }}
        <p></p>
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

ask/templates/new.html
{% extends 'base.html' %}

{% block content %}
    {% for question in questions %}
        <br>
        <a href="question/{{question.id}}">{{ question.title }}</a>
        <br>
    {% endfor %}
{% endblock content %}

ask/templates/popular.html
{% extends 'base.html' %}

{% block content %}
    {% for question in questions %}
        <br>
        <a href="/question/{{question.id}}">{{ question.title }}</a>
        <br>
    {% endfor %}
{% endblock content %}

ask/templates/question.html
{% extends 'base.html' %}


{% block content %}

    <p>Title:{{ question.title|title }}</p>
    
    <p>Text:{{ question.text }} </p>

    <br>
    <br>
    <br>

    {% for answer in question.answer_set.all %}
        <br>
        Answer:{{ answer.text }}
        <br>
    {% endfor %}

    <br>
    <br>
    <br>
    <br>
    <br>

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>

{% endblock content %}

ask/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ error }}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}